## Last changed: 2012-10-20 06:45:44 UTC
version "12.2I0 [slt-builder]";
system {
    root-authentication {
        encrypted-password "$1$3RRU14Td$9NyynPTnDBN82m79i1uG10"; ## SECRET-DATA
    }
    services {
        ssh;
        web-management {
            http {
                interface ge-0/0/0.0;
            }
        }
    }
    syslog {
        file messages {
            any any;
        }
    }
    license {
        autoupdate {
            url https://ae1.juniper.net/junos/key_retrieval;
        }
    }
}
interfaces {
    ge-0/0/0 {
        unit 0 {
            family inet {
                address 192.168.229.155/24;
            }
        }
    }
    lt-0/0/0 {
        unit 121 {
            encapsulation frame-relay;
            dlci 12;
            peer-unit 122;
            family inet {
                address 12.12.12.1/24;
            }
        }
        unit 122 {
            encapsulation frame-relay;
            dlci 12;
            peer-unit 121;
            family inet {
                address 12.12.12.2/24;
            }
        }
        unit 232 {
            encapsulation frame-relay;
            dlci 23;
            peer-unit 233;
            family inet {
                address 23.23.23.2/24;
            }
        }
        unit 233 {
            encapsulation frame-relay;
            dlci 23;
            peer-unit 232;
            family inet {
                address 23.23.23.3/24;
            }
        }
    }
    lo0 {
        unit 1 {
            family inet {
                address 1.1.1.1/32;
            }
        }
        unit 2 {
            family inet {
                address 2.2.2.2/32;
            }
        }
        unit 3 {
            family inet {
                address 3.3.3.3/32;
            }
        }
    }
}
security {
    forwarding-options {
        family {
            mpls {
                mode packet-based;
            }
        }
    }
    zones {
        security-zone trust {
            tcp-rst;
            host-inbound-traffic {
                system-services {
                    all;
                }
                protocols {
                    all;
                }
            }
            interfaces {
                ge-0/0/0.0;
            }
        }
    }
}
routing-instances {
    router-1 {
        instance-type virtual-router;
        interface lt-0/0/0.121;
        interface lo0.1;
    }
    router-2 {
        instance-type virtual-router;
        interface lt-0/0/0.122;
        interface lt-0/0/0.232;
        interface lo0.2;
    }
    router-3 {
        instance-type virtual-router;
        interface lt-0/0/0.233;
        interface lo0.3;
    }
}
